name: VirusTotal
on:
  release:
    types: [published]
jobs:

################################################################################

  scan:
    runs-on: ubuntu-latest
    steps:

      - name: Scan release asset
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: .zip$
